from enum import Enum

key1 = "LRRLLLRDRURUDLRDDURULRULLDLRRLRLDULUDDDDLLRRLDUUDULDRURRLDULRRULDLRDUDLRLLLULDUURRRRURURULURRULRURDLULURDRDURDRLRRUUDRULLLLLDRULDDLLRDLURRLDUURDLRLUDLDUDLURLRLDRLUDUULRRRUUULLRDURUDRUDRDRLLDLDDDLDLRRULDUUDULRUDDRLLURDDRLDDUDLLLLULRDDUDDUUULRULUULRLLDULUDLLLLURRLDLUDLDDLDRLRRDRDUDDDLLLLLRRLLRLUDLULLDLDDRRUDDRLRDDURRDULLLURLRDLRRLRDLDURLDDULLLDRRURDULUDUDLLLDDDLLRLDDDLLRRLLURUULULDDDUDULUUURRUUDLDULULDRDDLURURDLDLULDUDUDDDDD"
key2 = "RUURUDRDUULRDDLRLLLULLDDUDRDURDLRUULLLLUDUDRRUDUULRRUUDDURDDDLLLLRRUURULULLUDDLRDUDULRURRDRDLDLDUULUULUDDLUDRLULRUDRDDDLRRUUDRRLULUULDULDDLRLURDRLURRRRULDDRLDLLLRULLDURRLUDULDRDUDRLRLULRURDDRLUDLRURDDRDULUDLDLLLDRLRUDLLLLLDUDRDUURUDDUDLDLDUDLLDLRRDLULLURLDDUDDRDUDLDDUULDRLURRDLDLLUUDLDLURRLDRDDLLDLRLULUDRDLLLDRLRLLLDRUULUDLLURDLLUURUDURDDRDRDDUDDRRLLUULRRDRULRURRULLDDDUDULDDRULRLDURLUDULDLDDDLRULLULULUDLDDRDLRDRDLDULRRLRLRLLLLLDDDRDDULRDULRRLDLUDDDDLUDRLLDLURDLRDLDRDRDURRDUDULLLDLUDLDRLRRDDDRRLRLLULDRLRLLLLDUUURDLLULLUDDRLULRDLDLDURRRUURDUDRDLLLLLLDDDURLDULDRLLDUDRULRRDLDUDRLLUUUDULURRUR"
key3 = "URRRLRLLDDDRRLDLDLUDRDRDLDUDDDLDRRDRLDULRRDRRDUDRRUUDUUUDLLUURLRDRRURRRRUDRLLLLRRDULRDDRUDLRLUDURRLRLDDRRLUULURLURURUDRULDUUDLULUURRRDDLRDLUDRDLDDDLRUDURRLLRDDRDRLRLLRLRUUDRRLDLUDRURUULDUURDRUULDLLDRDLRDUUDLRLRRLUDRRUULRDDRDLDDULRRRURLRDDRLLLRDRLURDLDRUULDRRRLURURUUUULULRURULRLDDDDLULRLRULDUDDULRUULRRRRRLRLRUDDURLDRRDDULLUULLDLUDDDUURLRRLDULUUDDULDDUULLLRUDLLLRDDDLUUURLDUDRLLLDRRLDDLUDLLDLRRRLDDRUULULUURDDLUR"
key4 = "UULDRLUULURDRLDULURLUDULDRRDULULUDLLDURRRURDRLRLLRLDDLURRDLUUDLULRDULDRDLULULULDDLURULLULUDDRRULULULRDULRUURRRUDLRLURDRURDRRUDLDDUURDUUDLULDUDDLUUURURLRRDLULURDURRRURURDUURDRRURRDDULRULRRDRRDRUUUUULRLUUUDUUULLRRDRDULRDDULDRRULRLDLLULUUULUUDRDUUUDLLULDDRRDULUURRDUULLUUDRLLDUDLLLURURLUDDLRURRDRLDDURLDLLUURLDUURULLLRURURLULLLUURUUULLDLRDLUDDRRDDUUDLRURDDDRURUURURRRDLUDRLUULDUDLRUUDRLDRRDLDLDLRUDDDDRRDLDDDLLDLULLRUDDUDDDLDDUURLDUDLRDRURULDULULUDRRDLLRURDULDDRRDLUURUUULULRURDUUDLULLURUDDRLDDUDURRDURRUURLDLLDDUUDLLUURDRULLRRUUURRLLDRRDLURRURDULDDDDRDD"
key5 = "LLRUDRUUDUDLRDRDRRLRDRRUDRDURURRLDDDDLRDURDLRRUDRLLRDDUULRULURRRLRULDUURLRURLRLDUDLLDULULDUUURLRURUDDDDRDDLLURDLDRRUDRLDULLRULULLRURRLLURDLLLRRRRDRULRUDUDUDULUURUUURDDLDRDRUUURLDRULDUDULRLRLULLDURRRRURRRDRULULUDLULDDRLRRULLDURUDDUULRUUURDRRLULRRDLDUDURUUUUUURRUUULURDUUDLLUURDLULUDDLUUULLDURLDRRDDLRRRDRLLDRRLUDRLLLDRUULDUDRDDRDRRRLUDUDRRRLDRLRURDLRULRDUUDRRLLRLUUUUURRURLURDRRUURDRRLULUDULRLLURDLLULDDDLRDULLLUDRLURDDLRURLLRDRDULULDDRDDLDDRUUURDUUUDURRLRDUDLRRLRRRDUULDRDUDRLDLRULDL"

numpad = [	   [1],
			[2, 3, 4],
		 [5, 6, 7, 8, 9],
		 ['A', 'B', 'C'],
			  ['D']]

row = 2
col = 0
pos = numpad[row][col]

for move in key5:
	if pos == 1:
		if move == 'D':
			pos = numpad[1][1]
	elif pos == 2:
		if move == 'R':
			pos = numpad[1][1]
		elif move == 'D':
			pos = numpad[2][1]
	elif pos == 3:
		if move == 'U':
			pos = numpad[0][0]
		elif move == 'R':
			pos = numpad[1][2]
		elif move == 'D':
			pos = numpad[2][2]
		elif move == 'L':
			pos = numpad[1][0]
	elif pos == 4:
		if move == 'D':
			pos = numpad[2][3]
		elif move == 'L':
			pos = numpad[1][1]
	elif pos == 5:
		if move == 'R':
			pos = numpad[2][1]
	elif pos == 6:
		if move == 'U':
			pos = numpad[1][0]
		elif move == 'R':
			pos = numpad[2][2]
		elif move == 'D':
			pos = numpad[3][0]
		elif move == 'L':
			pos = numpad[2][0]
	elif pos == 7:
		if move == 'U':
			pos = numpad[1][1]
		elif move == 'R':
			pos = numpad[2][3]
		elif move == 'D':
			pos = numpad[3][1]
		elif move == 'L':
			pos = numpad[2][1]
	elif pos == 8:
		if move == 'U':
			pos = numpad[1][2]
		elif move == 'R':
			pos = numpad[2][4]
		elif move == 'D':
			pos = numpad[3][2]
		elif move == 'L':
			pos = numpad[2][2]
	elif pos == 9:
		if move == 'L':
			pos = numpad[2][3]
	elif pos == 'A':
		if move == 'U':
			pos = numpad[2][1]
		elif move == 'R':
			pos = numpad[3][1]
	elif pos == 'B':
		if move == 'U':
			pos = numpad[2][2]
		elif move == 'R':
			pos = numpad[3][2]
		elif move == 'D':
			pos = numpad[4][0]
		elif move == 'L':
			pos = numpad[3][0]
	elif pos == 'C':
		if move == 'U':
			pos = numpad[2][3]
		elif move == 'L':
			pos = numpad[3][1]
	elif pos == 'D':
		if move == 'U':
			pos = numpad[3][1]

print (pos)